### ISSUE TITLE
Add new frontend option to customer registration page to create addresses based on entered information

### ISSUE THREAD

**Issue by Michael-Herzog** [smartstore/SmartStoreNET#1380]
A simple checkbox would be sufficient. If checked one address should be created (marked as billing address)

With this option customers don't have to enter address data anew after their registration on first shop visit. 

Also add a backend option with which a shop admin can enforce this behavior without asking the customer.

**Comment by szokka** [comment]
A similar functionality already exists.
The system attempts to create a default address based on the information entered by the customer during registration.
The required fields of "Registration" and "Address" in Admin > Settings > Customer need to match so that the user enters all required information (e.g. street, city, postal code) in the registration form.
