### ISSUE TITLE
Adding or editing a category throws ambiguous call exception

### ISSUE THREAD

**Issue by SdKhalifaAhmed** [smartstore/SmartStoreNET#1502]
I have installed SmartStore on my server. everything is working fine except the add category module. when ever I try to Add or Edit any category an error pops saying  :

> Compilation Error Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.
> 
> Compiler Error Message: CS0121: The call is ambiguous between the following methods or properties: 'Telerik.Web.Mvc.UI.Fluent.GridToolBarCommandFactory.Template(System.Action>)' and 'Telerik.Web.Mvc.UI.Fluent.GridToolBarCommandFactory.Template(System.Func,object>)'

`Line 441:   .ToolBar(commands => commands.Template(CategoryProductsGridCommands))`

**Comment by Michael-Herzog** [comment]
Hi,

we can't reproduce this either in current development branch nor in the latest stable release. Which branch are you working with? Have you adapted anything?

Regards,
Michael

**Comment by Michael-Herzog** [comment]
Can't reproduce

**Comment by india-software** [comment]
Hi Guys, 
After working on it, we got the solution for this. So kindly try like this.
Hope will work
.ToolBar(commands => commands.Template(pp=>GridCommands(pp)))

**Comment by Michael-Herzog** [comment]
Hi,
can you tell me how to reproduce this error?
Regards,
Michael

**Comment by AbdonDeKousemaeker** [comment]
Hi,

I didn’t succeed in reproducing this…☹
But it happens if you’re change a lot in Catalog different categories and/or
change products adding picture, change things without leaving the function.

It always happens in the beginning of the project, when the customer is starting
to create catalog / products. Sounds like a stack overflow, or so.

Met vriendelijke groet, Best regards, Mit freundlichen Grüßen, Cordialement
KOOMBA b.v.

Abdon De Kousemaeker
Mobile: +31 612 8380 12
E-mail: abdon@koomba.eu
Postadres:
Postbus 1632
3260 BC  OUD-BEIJERLAND

Tel:  +31 10 204 55 25
Fax: +31 10 204 55 55

Brainpark II Rotterdam
Lichtenauerlaan 102
3062 ME  ROTTERDAM
www.koomba.eu
