### ISSUE TITLE
Make unavailable variant combinations unselectable

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#1644]
If at least one attribute combination has been selected, disable attributes which are not combinable with the current selection.

**Comment by stefanmuellerdo** [comment]
this issue has been reported to me on Monday 22.06. by a merchant, we reproduced it together in 3.2 live demo shop.

It would be nice if the non-selectable attributes were crossed out, grayed out or otherwise **pleasantly marked** as unavailable. Currently, the **red text** note "Variant not available" is not so optimal from a sales point of view. Red is evil :)

**Comment by mgesing** [comment]
Resolved.
