### ISSUE TITLE
Static image assets use 1 day expires by default, should be configurable (up to 1 week+)

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1782]
![Capture_030120082341AM](https://user-images.githubusercontent.com/15036268/71731574-59d27b00-2e02-11ea-871d-ea28f9bd8967.jpg)

**Comment by altmoola** [comment]
From `CachedFileResult.cs`:

    public DateTime ExpiresOnUtc { get; set; } = DateTime.UtcNow.AddDays(1);

I think this should be defined by mime type instead.

**Comment by muratcakir** [comment]
This setting is not THAT important, because revalidation occurs on EVERY hit to the file, regardless of its expiration time. If the file did not change since the last request, [an `OK` response (200) is sent to the browser](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Presentation/SmartStore.Web/Controllers/MediaController.cs#L307) without actually streaming the file. This instructs the client to load the local cached file.

When a file expires in the browser according to `ExpiresOnUtc `, the browser sends a `GET` instead of a `HEAD` request. The latter means 'revalidate', GET means 'gimme the file'. But Smartstore ALWAYS tries to serve files from server cache first. So in this case [a NotModified (304) response is sent](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Presentation/SmartStore.Web.Framework/Modelling/Results/FileResponder.cs#L50) to the client.

If the file did not exist in the server cache, it gets processed and [streamed to the browser](https://github.com/smartstore/SmartStoreNET/blob/86613cb1742b96e6934f8e665079e0c60253247c/src/Presentation/SmartStore.Web.Framework/Modelling/Results/FileResponder.cs#L81).
