### ISSUE TITLE
How to list brands on Navigation bar

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1854]
Hello!

I want to list the brands in the navigation bar. For example if I go to category sunglasses I want the brands of sunglasses to be listed(Ray Ban,Prada,Oakley....) . Should I create new categories with brands or is it possible to read the brands?
![brands-menu](https://user-images.githubusercontent.com/63068326/79073766-a0c8ea00-7ce8-11ea-9212-d318aa5490b1.jpg)

**Comment by altmoola** [comment]
There is no way to do this as far as I know. Your only option would be to create child brand categories in the Prescription glasses menu. This might look quite strange though because you'll see brand categories and sub categories and then the brands facet filter as well, but maybe this will work for you.

You might also consider assigning the product to both the Prescription glasses category and the child brand category (two category associations)
