### ISSUE TITLE
Product Attribute: Type Product and Stock quantity

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1908]
bug: when Attribute is Type Product inventary does not work properly.
Description in the image.

![1](https://user-images.githubusercontent.com/31403448/82322627-114fde80-99ec-11ea-93f3-95900b60b9d9.png)

![2](https://user-images.githubusercontent.com/31403448/82322631-144acf00-99ec-11ea-887b-97078c05fc60.png)

The product is repeated in the cart
![3](https://user-images.githubusercontent.com/31403448/82322643-1a40b000-99ec-11ea-9a64-2f43a7edb88b.png)
![4](https://user-images.githubusercontent.com/31403448/82322657-1dd43700-99ec-11ea-918f-515f1c6feca2.png)
![5](https://user-images.githubusercontent.com/31403448/82322800-58d66a80-99ec-11ea-93c5-f978f3e91427.png)

![6](https://user-images.githubusercontent.com/31403448/82322868-73104880-99ec-11ea-8604-e0d37b551428.png)

Eventually the inventory becomes negative
![7](https://user-images.githubusercontent.com/31403448/82322882-786d9300-99ec-11ea-91b4-881cec11c7c9.png)

**Comment by mgesing** [comment]
An inventory can become negative in this case if it is not managed by attributes. "Track inventory" causes an inventory check per shopping cart item but never cumulated. If attributes are selected or different, several shopping cart items are created and these are checked independently of each other because their attributes are different.
