### ISSUE TITLE
WebApi: When removing all categories from a product then the product is still displayed in the old categories

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2057]
When removing all categories from a product then the product is still displayed in the old categories. Only a rebuild of the catalogue index resolves this issue.

The call for removing the category mapping: `DELETE ~/Products({ProductID})/ProductCategories(0)`

Ps. Shortly after the product itself is deleted, don't know if this causes the issue.  This is the exact routine that we use when deleting a product:
`DELETE ~/Products({ProductID})/ProductCategories(0)`
`DELETE ~/Products({ProductID})/ProductManufacturers(0)`
Then some loops to delete LocalizedProperties, ProductVariantAttributes and RelatedProducts
Sleep(200)
`DELETE ~/Products({ProductID})`

Running on ST 3.2.2.2

**Comment by TripleNico** [comment]
Any news on this topic?

**Comment by mgesing** [comment]
This is by design. It's the expected behaviour. The product will no longer be displayed after the next periodic update of the search index (per scheduled task). A complete reindexing is not necessary. There is no way to trigger the indexing programmatically, because plugins do not know about each other.
