### ISSUE TITLE
Blog Image upload option does not allow anything except ico files

### ISSUE THREAD

**Issue by merashmita** [smartstore/SmartStoreNET#2151]
![image](https://user-images.githubusercontent.com/20870793/98793115-703b6100-242d-11eb-9c1a-6c4ede618b6d.png)

The admin blog editor, does not allow to add normal jpg/jpeg images or drag drop.

**Comment by merashmita** [comment]
![image](https://user-images.githubusercontent.com/20870793/98799989-d2985f80-2435-11eb-9edd-cf83d7f66657.png)

**Comment by Michael-Herzog** [comment]
This problem was fixed by [this commit](https://github.com/smartstore/SmartStoreNET/commit/e83700773f595ed238965d0570ca14e86f675d64). Seems like you're working with 4.x which is the current development branch. You should work in 4.1.x,

To fix your problem you must restore the original MediaSettings here: Admin > Configuration > Settings > Media
Just enter: png jpg jpeg gif webp bmp svg ico

**Comment by merashmita** [comment]
Michael, this helped. Good.
