### ISSUE TITLE
Product: MergedDataValues is null if product has an attribute of type 'file-upload'.

### ISSUE THREAD

**Issue by szokka** [smartstore/SmartStoreNET#2189]
For products with attribute combinations with set price, this results in the default price being used for calculations. The correct price is only displayed in the product detail.

**Comment by mgesing** [comment]
The strict interpretation of attribute combinations require that all selected attributes are included, otherwise there is no match.
However, this is not possible with file uploads because they take place after the attribute combination has been created.

The goal is to identify attribute combinations only by multi-value attribute types (related [issue](https://github.com/smartstore/Smartstore/issues/341)). However, it is not possible to implement that for version 4.1.1.
