### ISSUE TITLE
WebApi: New MediaFiles endpoint example

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2198]
From the release notes: 

- Web API: now supports the widely extended version 4 of OData. New endpoints for uploading and managing media files have been added to the API.

I conclude that you can now finally control all Media components via the WebApi. I see this also reflected in the Swagger UI However, when I try it on the Demo Website in Swagger, an exception occurs (as seen in the log section): `Value cannot be null. Parameter name: mediaFile` Also tested with 4.1.1 test environment and it doesn't seem to work properly there either.

My question to is  how the MediaFiles endpoint can be used. ideally I'll would like to receive an example (based on Microsoft.OData.Client class) if that's possible?

**Comment by TripleNico** [comment]
Regarding this topic, i'am hitting an dead end and since ProductPicture etc.. isn't available in the WebApi we currently have no way to update our application to v4 and get is running, hopefully this can looked in to a.s.a.p.

In the meantime some additional info:

If you use the `OData connected service` from Microsoft for test than it failes to deserialise the JSON to the OData object. While if you check the RAW content in Fiddler that it seems all good. But i think there has been a mixed up in the metadata because the `~/odata/v1/MediaFiles` is op type MediaFile:
```json
{
  "@odata.context": "http://MySite/odata/v1/$metadata#MediaFiles/SmartStore.Core.Domain.Media.MediaFile",
  "value": [
    {
      "@odata.type": "#SmartStore.Core.Domain.Media.MediaFile",
      "FolderId": 2,
      "Name": "all-star-charcoal.jpg",
      "Alt": null,
      "Title": null,
      "Extension": "jpg",
      "MimeType": "image/jpeg",
      "MediaType": "image",
      "Size": 30074,
      "PixelSize": 48400,
      "Metadata": null,
      "Width": 220,
      "Height": 220,
      "CreatedOnUtc": "2019-11-06T07:58:45.177Z",
      "UpdatedOnUtc": "2021-02-10T14:20:19.67Z",
      "IsTransient": false,
      "MediaStorageId": null,
      "Id": 2
    }
  ]
}
```

While if you check the `~/odata/v1/$metadata` is seems it is of type `FileItemInfo`? So my guess is that the deserialiser is trying to deserialise something to the wrong object?
```xml
<EntitySet Name="MediaFiles" EntityType="SmartStore.WebApi.Models.OData.Media.FileItemInfo"/>
```

**Comment by mgesing** [comment]
> since ProductPicture etc.. isn't available in the WebApi v4...

I can see ProductPictures endpoints. What exactly is not available?

**Comment by TripleNico** [comment]
> > since ProductPicture etc.. isn't available in the WebApi v4...
> 
> I can see ProductPictures endpoints. What exactly is not available?

Sorry my bad, i mean endpoint ~/Picture this is not available anymore. In v3 i used endpoint `~/Picture` to removed them if a category/brand/product is deleted.

For product pictures i used in v3 endpoint '~/api/v1/Uploads/ProductImages' and for manufacture and category pictures i used the Import Profiles to manage this. With v4 i was hoping to convert it al to use the '~/MediaFiles' endpoint for GET/POST/PATCH pictures of products/manufacturers/categories. But it seems that with the Visual Studio extension `OData Connected Service` the deserialization of 'MediaFiles' and 'MediaFolders' result in an exception: 
```
InvalidOperationException: The response payload is a not a valid response payload. Please make sure that the top level element is a valid Atom or JSON element or belongs to 'http://docs.oasis-open.org/odata/ns/data' namespace.
```

Checking the raw response data is seems correct:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8; odata.metadata=minimal
Expires: -1
Server: Microsoft-IIS/10.0
SmartStore-Net-Api-AppVersion: 4.1.1.0
SmartStore-Net-Api-Version: 1 4.1.1
SmartStore-Net-Api-MaxTop: 99999
SmartStore-Net-Api-Date: 2021-02-23T07:26:18.1898007Z
SmartStore-Net-Api-CustomerId: 5569
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Tue, 23 Feb 2021 07:26:17 GMT
Content-Length: 547

{
  "@odata.context":"http://MySite/odata/v1/$metadata#MediaFiles/SmartStore.Core.Domain.Media.MediaFile","value":[
    {
      "@odata.type":"#SmartStore.Core.Domain.Media.MediaFile","FolderId":2,"Name":"all-star-charcoal.jpg","Alt":null,"Title":null,"Extension":"jpg","MimeType":"image/jpeg","MediaType":"image","Size":30074,"PixelSize":48400,"Metadata":null,"Width":220,"Height":220,"CreatedOnUtc":"2019-11-06T07:58:45.177Z","UpdatedOnUtc":"2021-02-10T14:20:19.67Z","IsTransient":false,"MediaStorageId":null,"Id":2
    }
  ]
}
```

I think this is because what i wrote earlier, the `@odata.type` describes type `MediaFile` but the OData MetaData describes type `FileItemInfo`

**Comment by mgesing** [comment]
'Picture' was renamed to 'MediaFile' and extended in the process of the media manager, so it's still available.
GET /MediaFiles(123) and GET /MediaFiles works for me. Raw POST, PUT and PATCH are forbidden because there are further endpoints for it like [SaveFile](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L445).

So this probably seems to be an issue with your auto-generated code or how the OData service is configured in your client.

There is not much I can contribute here because I've never used or wrote such an OData Connected Service client.
I have created a VS 2019 preview console app and successfully included a connection to my OData service using both OData Connected Service or Unchase OData Connected Service. Anyway, the auto-generated code compiles without errors. But to connect to my OData service, I would have to further investigate this now, write the client, include API authorization....

**Comment by TripleNico** [comment]
Thanks for the extra info. Will debug some more with the `OData Connected Service Client` to see where the problem lays. Generating and compiling is indeed not the problem but when executing the Query then upon receiving the response the deserialisation fails. **Tip**: if you plan to build your own app for testing purpose then you can use the OData Client event `SendingRequest2` to handle the authorisation. If you want a jump start i can send you some code.

Great that you further explained how the endpoints are now working, i didn't understand this by only looking at the Swagger documentation. I know this is on the roadmap to update. 

Just to get thing clear few use cases:

1. Query `GET /MediaFiles` see if picture exists 
2. If not call extension `.SaveFile`
2. If it exists, check if the image is the same (can have the same filename) by comparing properties `Size`, `CreatedOnUtc` and `UpdatedOnUtc` of object type `FileItemInfo` If it's not equal then call extension `.SaveFile`
3. If a Product/Manufacturer/Category is removed via the WebApi call `POST /MediaFiles(123)/DeleteFile`

Are these steps correct and most efficient?

**Comment by mgesing** [comment]
SaveFile is for _uploading_ media files. It has an optional parameter "[DuplicateFileHandling](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L494)" that can handle duplicate files (passed as a ContentDisposition header together with multipart file data). Uploading files was not possible using OData endpoints before v.4., so I'm asking myself what your client actually did here?

Product, category and manufacturer are soft-deletable entities. They are marked as deleted but not physically removed from database. So you don't need to delete an image or media file associated with one of these entities when it's deleted. You actually should not do this because since version 4.0 media files can be assigned to multiple entities. You also do not need to delete the assignment of the image to a product because the product entity is soft-deletable. In other words, if you delete a product, category or manufacturer via API you don't need to do anything else. The backend does nothing else here either.

**Comment by TripleNico** [comment]
I didn't found the `SaveFile` extension being used in the Client example app you provide is that correct? Also why is there an extension `SaveFile` while OData uses [SetSaveStream](https://docs.microsoft.com/en-us/dotnet/api/microsoft.odata.client.dataservicecontext.setsavestream?view=odata-client-7.0) for this?

The reason i queried all those endpoints before is determine if an image exists and if it needs to be updated or deleted. In all times i want to prevent uploading all images since our Sync application is running every hour to sync SmartStore with our CRM system. Meaning handling products/categories/manufacturers/customers/customerroles/adresses/DependingPrices/orders/etc.. every hour would then also causes all images (few thousand) to being uploaded.

Regarding the deletion thanks for making that clear to me. In OData v3 i noticed that this wasn't always the case. Are the indexes than also updated? Meaning a product isn't visible anymore in a category, etc... Or it is simpler and can i assume when i DELETE an entity that this acts the same way as if a user in the backend clicks on Remove?

If you find the time it would be great if you can try it for yourself using the OData Connected Service to test if all is compliant. That would help me out a lot! ;-)

**Comment by mgesing** [comment]
As far as I remember, all endpoints can be tested by our API client. There is an "open file" button to select an image being uploaded.

SetSaveStream does not tell me anything. I cannot find any Microsoft.OData.Client dependency in our code.

There is also a [FileExists](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L283
) method.

Do you mean search index? Yes, when a product is deleted, MegaSearch is notified via a hook and takes this into account during the next scheduled indexing.

If an entity is soft-deletable (aka [ISoftDeletable](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Core/Domain/Catalog/Product.cs#L20)) like product, category, manufacturer then it's never physically deleted. No matter if one of these entities is deleted via API or backend, the result is the same because the same service method is executed. If you physically delete a product, you will get problems in the form of inconsistent data (e.g. order items).

[FileItemInfo](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Models/OData/Media/FileItemInfo.cs) is an API specific model acting as a wrapper class that contains MediaFile by property "File" but also some other properties. The purpose is to return additional data not contained in MediaFile at the same time, without risking collision when the core is changed.

**Comment by TripleNico** [comment]
Thanks for confirming that your application is working. That pointed me in the right direction regarding Uploading files. I ended up by remodelling the currently used endpoint `POST ~/api/Uploads/ProductImages` to work with the new `POST ~/odata/v1/MediaFiles/SaveFile` endpoint. This seems to be working except i have to determine the path:
```
Invalid path 'catalog'. Valid path expression is: {albumName}[/subfolders]/{fileName}.{extension}\r\nParameter name: path
```
Question here s what are the paths for Product, Category and Manufacturer? The path `catalog` was just a try.

I still have to figure out what is going wrong with the Deserialization of `GET ~/MediaFiles` in order to determine file exists and file changed, etc...

Regarding the Delete, thanks for clearing that. That would save some extra code so i will have a cleanup of my code removing all additional code that comes after DELETE of a object. Since it is soft-deletable wouldn't that cluther the database overtime? I can understand that items that are linked to Orders isn't possible but how about a Product that was never purchased/used?

**Comment by TripleNico** [comment]
Additional questions/requests:

1. I see currently multiple files in one upload is not supported, will this be added?
2. Is it possible to add the linking of objects? For example, add SKU in content-disposition so after upload SmartStore links it to Product with SKU XX. Same for Category and Manufacture? Else i would have to do upload of a file in two steps. Step 1: Upload the file. Step 2: Find the new File and link the ID to a Product, Category or Manufacturer
3. If step 2 is possible it would be great if the DisplayOrder in case of Product would also be excepted.

**Comment by mgesing** [comment]
Path is always: `catalog/<file name>` (e.g. catalog/my-image.jpg). You can see them in the right panel of the Media-Manager when selecting an image.

Yes, at some point the database will become very large if soft-deletable entities are deleted again and again, but at some point we will also have a trash function for this.

`GET /MediaFiles` returns the entity instead of FileItemInfo to support all ODataQueryOptions when querying lists of entities. Maybe your auto-generated code generator can't make the distinction between these two models based on the metadata. Could you please test and replace the code of the `GET /MediaFiles` API endpoint by following code:

```
[WebApiQueryable]
[WebApiAuthenticate]
public IHttpActionResult Get(ODataQueryOptions<MediaFile> queryOptions)
{
	IQueryable<MediaFile> query = null;

	var hasClientPaging = Request?.RequestUri?.Query?.Contains("$top=") ?? false;
	if (!hasClientPaging)
	{
		var maxTop = WebApiCachingControllingData.Data().MaxTop;
		var top = Math.Min(this.GetQueryStringValue("$top", maxTop), maxTop);

		query = queryOptions.ApplyTo(GetEntitySet(), new ODataQuerySettings { PageSize = top }) as IQueryable<MediaFile>;
	}
	else
	{
		query = queryOptions.ApplyTo(GetEntitySet()) as IQueryable<MediaFile>;
	}

	var files = query.ToList();
	var result = files.Select(x => Convert(Service.ConvertMediaFile(x)));

	return Ok(result);
}
```

Does your client work with this? It may have a disadvantage because I am not sure whether all ODataQueryOptions are really taken into account.

Question 1, 2, 3: No, not for MediaFiles endpoints. They are meant to map the media infrastructure one-to-one, no custom catalog stuff here. By the way, for uploading product images there is an older, non-OData, generic multipart REST endpoint [`POST /api/v1/Uploads/ProductImages`](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/Api/UploadsController.cs#L79) that's handling multiple uploads including product media file assignments. It has also a duplicate file handling, and you also also send a picture ID aka Media File ID to sync existing images, if you know it. The DisplayOrder is simply increased here by one for each image uploaded per product. Docu is [here](http://docs.smartstore.com/display/SMNET40/Uploading+Product+Images) but it only works with product images, not for category or manufacturer images.

**Comment by TripleNico** [comment]
> Path is always: `catalog/<file name>` (e.g. catalog/my-image.jpg) for catalog related media files. You can see the path in the right panel of the Media-Manager when selecting an image.
> 
Thanks got it! Also the tip for looking in the Media-Manager is very helpful! Is saw in the marketplace that there is now also a plugin for documents etc.. at products. Would the folder then just be `FileManager`? And is there also an extra API endpoint for mapping MediaFile to the product then?

> Yes, at some point the database will become very large if soft-deletable entities are deleted again and again, but at some point we will also have a trash function for this.
>
That would be great (and necessary), keeping things clean which off course benefits the performance!

>GET /MediaFiles returns the entity instead of FileItemInfo to support all ODataQueryOptions when querying lists of entities. Maybe your auto-generated code generator can't make the distinction between these two models based on the metadata.
>
That's understandable but it conflicts with the MetaData XML stating a different object. I guess the client code needs to be aware of dynamic types of some sort?

> Could you please test and replace the code of the GET /MediaFiles API endpoint
>
That seems to do the trick and returns the right (expected) object. However things brings a new exception:
```
Microsoft.OData.ODataException: 'The Id cannot be computed, since the navigation source 'File' cannot be resolved to a known entity set from model.'
```

This was the RAW response:
```RAW
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; odata.metadata=minimal; charset=utf-8
Expires: -1
Server: Microsoft-IIS/10.0
SmartStore-Net-Api-AppVersion: 4.1.1.0
SmartStore-Net-Api-Version: 1 4.1.1
SmartStore-Net-Api-MaxTop: 120
SmartStore-Net-Api-Date: 2021-02-26T08:16:15.0498239Z
SmartStore-Net-Api-CustomerId: 5569
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Fri, 26 Feb 2021 08:16:15 GMT
Content-Length: 655

{
  "@odata.context": "http://MySite/odata/v1/$metadata#MediaFiles",
  "value": [
    {
      "Id": 2,
      "Directory": "content",
      "Path": "content/all-star-charcoal.jpg",
      "Url": "/media/2/content/all-star-charcoal.jpg",
      "ThumbUrl": "/media/2/content/all-star-charcoal.jpg?size=256",
      "File": {
        "FolderId": 2,
        "Name": "all-star-charcoal.jpg",
        "Alt": null,
        "Title": null,
        "Extension": "jpg",
        "MimeType": "image/jpeg",
        "MediaType": "image",
        "Size": 30074,
        "PixelSize": 48400,
        "Metadata": null,
        "Width": 220,
        "Height": 220,
        "CreatedOnUtc": "2019-11-06T07:58:45.177Z",
        "UpdatedOnUtc": "2021-02-10T14:20:19.67Z",
        "IsTransient": false,
        "MediaStorageId": null,
        "Id": 2
      }
    }
  ]
}
```

**Comment by mgesing** [comment]
Names of the default folders are located [here](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Services/Media/Album/SystemAlbumProvider.cs#L28
). New (sub-)folders can be created via `POST /MediaFolders/CreateFolder {"Path":"content/my-folder"}`, [link](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFoldersController.cs#L205).

Media files can be assigned to products by `POST /Products(<Product.Id>)/ProductPictures(<MediaFile.Id>)`, [link](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/ProductsController.cs#L304
). The body is [ProductMediaFile](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Core/Domain/Catalog/ProductMediaFile.cs#L29) content.

Please attach the code of your client here so I can take a closer look at the error message and to ensure that any changes do not create new errors.

**Comment by TripleNico** [comment]
> Names of the default folders are located [here](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Services/Media/Album/SystemAlbumProvider.cs#L28). New (sub-)folders can be created via `POST /MediaFolders/CreateFolder {"Path":"content/my-folder"}`, [link](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFoldersController.cs#L205).
> 
> Media files can be assigned to products by `POST /Products(<Product.Id>)/ProductPictures(<MediaFile.Id>)`, [link](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/ProductsController.cs#L304). The body is [ProductMediaFile](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Core/Domain/Catalog/ProductMediaFile.cs#L29) content.
> 
Great, thanks for the info!

> Please attach the code of your client here so I can take a closer look at the error message and to ensure that any changes do not create new errors.
>

Sure, what would you like to see (since i have to strip down some code)? Or should i create a little sample project for you?

**Comment by mgesing** [comment]
Code or sample project where I can reproduce the error.

**Comment by TripleNico** [comment]
> Code or sample project where I can reproduce the error.

I've created a sample project for you using [Microsoft OData Connected Service](https://docs.microsoft.com/en-us/odata/connectedservice/getting-started). If correctly you should have a Github invite to the private repository.

It uses the API from your Demo website. Just download and run it. Please note that you first have to change the `Get ~/MediaFiles` in the webapi to this https://github.com/smartstore/SmartStoreNET/issues/2198#issuecomment-786036554 before it works. Or just adjust the API link and keys to your development one.

**Comment by mgesing** [comment]
I've [updated the API configuration](https://github.com/smartstore/SmartStoreNET/commit/5861bfe2f2a1fc9b093ed9c2b3e8f2d9eda5a1e9) that make MediaFiles and MediaFolders work with your sample code. It returns IEnumerable of MediaFile again (not MediaFileInfo), so you have to update your API plugin and your OData connected service.

But.... the OData Connected Service generally creates wrong code for OData actions and functions. Examples: it incorrectly generates FileItemInfoSingle instead of IEnumerable as return value for GET /MediaFiles/GetFilesByIds(Ids=[1,2,3]) and it often uses the wrong HTTP method (GET instead of POST) which will result in a 404...

We have to check, re-configure and test all OData actions and functions with regard to their configuration to see whether an auto-generated code generator translates it correctly. This is really a lot of work to do and will take its time. We'll have to do this later. I have created an [issue](https://github.com/smartstore/Smartstore/issues/389) for it.

If I were you, I would switch to generic API requests like in the Smartstore API client to get back more control over client code.

**Comment by TripleNico** [comment]
Due to your update all seems to be working now, thanks!

I can understand that checking the API with the MSFT OData Client code generator would be alot of work. It would though be an extra plus for other customers out there than want to start coding real quickly with your WebApi.

I do have a question though the parameters like `DuplicateFileHandling` should they have their own  form-data like this:
```
-----------9FB32361-6F89-49D8-B52C-1F4B4C4D5761
Content-Disposition: form-data; name="DuplicateFileHandling"

Overwrite
-----------9FB32361-6F89-49D8-B52C-1F4B4C4D5761
Content-Disposition: form-data; name="file"; PictureId="14016"; Path="content\14210_1.jpg"; DuplicateFileHandling="Overwrite"; filename="14210_1.jpg"
Content-Type: image/jpeg
```

or should it be combined with the file info like this:
```
-----------9FB32361-6F89-49D8-B52C-1F4B4C4D5761
Content-Disposition: form-data; name="file"; PictureId="14016"; Path="content\14210_1.jpg"; DuplicateFileHandling="Overwrite"; filename="14210_1.jpg"
Content-Type: image/jpeg
```

**Comment by mgesing** [comment]
For multipart content it's the second one, Content-Disposition parameter on the file content part, because it expects exact one content part here. Otherwise it's a JSON property in the posted content:
```
POST ~/MediaFiles(14332)/MoveFile 
{"DestinationFileName":"catalog/rename-me.jpg","DuplicateFileHandling":"Rename"}

```

**Comment by TripleNico** [comment]
Great, than i will add it to the form-data of the file itself. Although this raises another question: If `DuplicateFileHandling` is `Overwrite` on [SaveFile](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L442) should the Identifier described as `Id` be added to the file form-data or to it's own form-data? In other words should it be this:

```
-----------9FB32361-6F89-49D8-B52C-1F4B4C4D5761
Content-Disposition: form-data; name="Id"

8
-----------9FB32361-6F89-49D8-B52C-1F4B4C4D5761
Content-Disposition: form-data; name="file"; Path="catalog\14210_1.jpg"; DuplicateFileHandling="Overwrite"; filename="14210_1.jpg"
Content-Type: image/jpeg
```

or should it be like this:
```
-----------9FB32361-6F89-49D8-B52C-1F4B4C4D5761
Content-Disposition: form-data; name="file"; Id="14016"; Path="content\14210_1.jpg"; DuplicateFileHandling="Overwrite"; filename="14210_1.jpg"
Content-Type: image/jpeg
```

**Comment by mgesing** [comment]
As mentioned, SaveFile is limited to exactly [one multipart](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L469) so the parameters (Path, IsTransient, DuplicateFileHandling) must be passed through that multipart.

In principle, these methods do nothing more than collect data and parameters and use it to call the corresponding MediaService method. The duplicate checks are made by file path here, not by ID. Details can be viewed in method [CheckUniqueFileName](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Services/Media/MediaService.cs#L278).

**Comment by TripleNico** [comment]
Aha, that explains the current behaviour i'm seeing. So overwriting a file with a different file name results not in a overwrite but in a new file, correct?

For example filename `1234-1.jpg` is not the same as `1234_1.jpg` correct? If so if one want to use the `Overwrite` function the filenames have to match else it won't be overwritten?

**Comment by mgesing** [comment]
> So overwriting a file with a different file name results not in a overwrite but in a new file, correct?

Yes, if no file exists with this name.

> For example filename 1234-1.jpg is not the same as 1234_1.jpg correct?

Yes.

> If so if one want to use the Overwrite function the filenames have to match else it won't be overwritten?"

Yes, the names have to match.

> Additional what would be the approach to Overwrite a jpg with png?

MoveFile?

**Comment by TripleNico** [comment]
> MoveFile?
>

Alright so use [MoveFile](https://github.com/smartstore/SmartStoreNET/blob/bb559b3aab2ff66175dbf8944e377a71d8e62373/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L363) to Upload a new file that overwrites a existing file?

For example:
Existing file is called `1234-1.jpg` and the new `png` file is called `1234_1.png` then i will call `MoveFile` with `DuplicateFileHandling` set to `Overwrite`, correct?

Or do i first have to use `SaveFile` for the upload of the new PNG and then call `MoveFile` to Overwrite the existing jpg? Wil this also inherit then the mapping to a product?

Or option 3 use `SaveFile` to upload and map it to a product and call `DeleteFile` afterwords on the old `JPG`?

**Comment by muratcakir** [comment]
You cannot change a file's MIME type during a move operation: https://github.com/smartstore/SmartStoreNET/blob/bb559b3aab2ff66175dbf8944e377a71d8e62373/src/Libraries/SmartStore.Services/Media/MediaService.cs#L898

Because, simply said, JPG is not PNG. Therefore option 3 is the way to go.

**Comment by TripleNico** [comment]
> You cannot change a file's MIME type during a move operation:
> 
> https://github.com/smartstore/SmartStoreNET/blob/bb559b3aab2ff66175dbf8944e377a71d8e62373/src/Libraries/SmartStore.Services/Media/MediaService.cs#L898
> 
> Because, simply said, JPG is not PNG. Therefore option 3 is the way to go.

Thanks for confirming my hunch. Option 3 it is! I just realised that i can always call `SaveFile` for `Overwrite` because:

1. If the filename is the same (that means also the extension) than the response body will contain the same Id as used for upload
2. If the response body Id is not the same as one used for uploading then SmartStore has created a new MediaFile meaning we can Delete the previous one.

Just double checking, if i call `DeleteFile` will this remove also any mapping to objects?

**Comment by mgesing** [comment]
Yes, as long as you call it with the appropriate parameters:
https://github.com/smartstore/SmartStoreNET/blob/bb559b3aab2ff66175dbf8944e377a71d8e62373/src/Plugins/SmartStore.WebApi/Controllers/OData/MediaFilesController.cs#L430-L431
https://github.com/smartstore/SmartStoreNET/blob/bb559b3aab2ff66175dbf8944e377a71d8e62373/src/Libraries/SmartStore.Services/Media/MediaService.cs#L483

**Comment by TripleNico** [comment]
Thanks, it seems i've got things up and running now. Although i noticed when i bulk(1000+) upload images for products then not all products get a thumbnail generated. If i do some test than in some categories the thumbnails of the product are not showing but if i click on the product then all images are there and correct.

Can it be that the bulk upload is to fast? Or maybe the thumbnails are generated in batches and some are missed by this? I do want to test is i put in a sleep of let's say 1 second per upload if this fixes the issue.

**Comment by mgesing** [comment]
Please ensure that [Product.MainPictureId](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Core/Domain/Catalog/Product.cs#L823) references the main picture of a product. It is responsible for displaying the preview image in for example product lists.

**Comment by muratcakir** [comment]
INFO: thumbnails are never created during upload, but lazily on first hit. Therefore: throttling upload won't fix anything.

**Comment by TripleNico** [comment]
> Please ensure that [Product.MainPictureId](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Core/Domain/Catalog/Product.cs#L823) references the main picture of a product. It is responsible for displaying the preview image in for example product lists.

Thanks for notifying this. Never thought of it because if you upload a image for the first time then it is set by SmartStore self. But if you remove the first image afterwords, upload a new one than the old one isn't overwritten. Thanks to your hint i now have a function that checks after upload if the `MainPictureId` matches the first MediaFileId found in `Product.ProductPictures` if not then it will update it with the first one. This seems to resolve the issue.

> INFO: thumbnails are never created during upload, but lazily on first hit. Therefore: throttling upload won't fix anything.

Aha, thanks for clarifying that. That confirms indeed why the extra sleep didn't do anything ;-)
